dependencies:
- name: devplat-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: jx-archmeeting
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: jx-go
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: jx-neusprojekt
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: jx-testbeforedemo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
